### ISSUE TITLE
Importing an empty json file under "Import Settings" freezes import

### ISSUE THREAD

**Issue by dreiekk** [Maveo/Spark-webclient#2]
Steps to reproduce:
In the "Server Settings" view, import an empty valid json file (contents: `{}`).

The website will show a loading spinner in the upper right corner with text "Importing..." forever.

**Comment by KGS501** [comment]
SACH MAL...

Erstens was ist das überhaupt für ein RANZIGES Issue?!?!? Vieleicht erstmal hallo sagen dich vorstellen und dann schön beschreiben, worum gehts überhaupt?, ist das wirkllich so schlimm??, hat es dich persönlich oder familiär eingeschränkt???!

Zweites warum sieht das so grüze formatiert aus?? Wozu ist denn diese ganze kack WEbsite in Markdown geschrieben????? Mal vllt Healines kursiv etc damit man auch schön lesen kann  und nciht nur monotoner text einen anstarrt. Bilder wären auch schöne gewesen aber was reg ich mit noch auf....

und drittens
WARUM WERDE ICH ASSIGNED?!?!??!?! Was soll ich da bitteschön machen?!?! Dem Bug gut zureden und hoffen, dass er sich auflöst. !??!?!? Alternativ könnt ich auch noch versuchen den sog. "loading spinner" (??) in css wegzuprogrammieren. Dann schreibt vllt auch keiner keine mehr so ein BESCHISSENES Issue darüber. aber problem ist dann auch nciht weg. tja machste nix. Und ich schonmal garnicht

Und viertens

WARUM lößt du das problem nicht se3lbst halloooooo? Wozu ist man denn PRogrammierer?!? Hier gibts nen affengeiles Feature das heißt Pull Request. DA kann man selbst sachen einreichen. WEr sich in sein GitHub Profil schriebt "currently working on Spark web client🤓" Der MUSSS AUCHMAL DRAN ARBEITENNN MAAAAAAAN

**Comment by skillor** [comment]
Maveo/Spark@eb01d2d9ab8d42c006063f8fec50007679402948
